import type { DifficultyTier, LevelConfig } from '../src/lib/agents/types.js'

export const LEVEL_CONFIGS: Record<DifficultyTier, LevelConfig> = {
  1: {
    level: 1,
    label: 'Rookie',
    provider: 'openai',
    lawyerModel: 'gpt-4o-mini-2024-07-18',
    judgeModel: 'gpt-5',
    temperature: 0.6,
    reasoningNotes: 'Favor direct arguments, obvious contradictions, and easy-to-follow evidence chains.',
    maxOutputTokens: 700,
    objectionAggressiveness: 'low',
    witnessConsistencyStrictness: 'medium',
    retrievalEnabled: false,
    lawyerVoice: 'alloy',
    judgeVoice: 'sage',
  },
  2: {
    level: 2,
    label: 'Junior',
    provider: 'openai',
    lawyerModel: 'gpt-4o-mini-2024-07-18',
    judgeModel: 'gpt-5',
    temperature: 0.65,
    reasoningNotes: 'Pressure weak logic, but leave enough openings for a prepared player to recover.',
    maxOutputTokens: 850,
    objectionAggressiveness: 'medium',
    witnessConsistencyStrictness: 'medium',
    retrievalEnabled: false,
    lawyerVoice: 'alloy',
    judgeVoice: 'sage',
  },
  3: {
    level: 3,
    label: 'Senior',
    provider: 'openai',
    lawyerModel: 'gpt-4o-mini-2024-07-18',
    judgeModel: 'gpt-5.5',
    temperature: 0.7,
    reasoningNotes: 'Exploit ambiguity, connect contradictions, and punish unsupported claims quickly.',
    maxOutputTokens: 950,
    objectionAggressiveness: 'high',
    witnessConsistencyStrictness: 'high',
    retrievalEnabled: false,
    lawyerVoice: 'verse',
    judgeVoice: 'sage',
  },
  4: {
    level: 4,
    label: 'Partner',
    provider: 'openai',
    lawyerModel: 'gpt-4o-mini-2024-07-18',
    judgeModel: 'gpt-5.5',
    temperature: 0.7,
    reasoningNotes: 'Assume a skilled opponent and challenge every unsupported inference with speed and precision.',
    maxOutputTokens: 1100,
    objectionAggressiveness: 'high',
    witnessConsistencyStrictness: 'high',
    retrievalEnabled: false,
    lawyerVoice: 'verse',
    judgeVoice: 'ballad',
  },
  5: {
    level: 5,
    label: 'Legend',
    provider: 'openai',
    lawyerModel: 'gpt-4o-mini-2024-07-18',
    judgeModel: 'gpt-5.5',
    temperature: 0.75,
    reasoningNotes: 'Use layered reasoning, retrieval-backed references, and aggressive rebuttal under uncertainty.',
    maxOutputTokens: 1300,
    objectionAggressiveness: 'extreme',
    witnessConsistencyStrictness: 'high',
    retrievalEnabled: true,
    lawyerVoice: 'verse',
    judgeVoice: 'ballad',
  },
}

export function getLevelConfig(level: DifficultyTier): LevelConfig {
  return LEVEL_CONFIGS[level]
}
